### ISSUE TITLE
Evaluate arbitrary many arguments 

### ISSUE THREAD

**Issue by danhab99** [geo-ant/varpro#31]
https://github.com/geo-ant/varpro/blob/f2adeec4a100714d7915fb7014ce09d91246d299/src/basis_function/mod.rs#L22

I noticed this comment while trying to solve my problem. I want to control how precice the solver gets to be by inputting the number of parameters to try dynamically. How do I do this with varpro?

**Comment by geo-ant** [comment]
Hi! There are two APIs that allow you to interface with the library. The one that you are referring to is the SeparableModel(Builder). I did not design it in a way that lends itself to work with a runtime known number of arguments for the basis functions. I think it makes usability just a bit nicer like that, but it does prevent you from adapting it to your usecase. 

However, there is a second interface to the functionality. That's the [SeparableNonlinearModel](https://docs.rs/varpro/0.8.0/varpro/model/trait.SeparableNonlinearModel.html) trait. If you implement that for your problem, I'm sure you'll be able to achieve what you want. The documentation gives a detailed example. If you have more questions I'll try and help you.

**Comment by geo-ant** [comment]
Hey @danhab99, just checking if you are happy with my suggestion or if you need further assistance. If you don't need more help I'd like to close this issue.

**Comment by danhab99** [comment]
Hey @geo-ant, I think implementing this trait is the way to go.. I haven't gotten something working yet but this is my first rust project so...

Thanks for the advice tho

**Comment by geo-ant** [comment]
Ok great, always cool to see new people getting into the language. I'll close the issue for now, but please feel free to open up a new one anytime you feel stuck. I always try to help, but my response times may vary.
